import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";

const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const productNames:Record<string,string>={squash:"Calabaza",watermelon:"Sandía",pineapple:"Piña",platano:"Plátano",papaya:"Papaya","yuca-parafinada":"Yuca parafinada","melon-golden-honeydew":"Melón Golden Honeydew",other:"Otro"};
function safe(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]||char))}
type Inquiry={name:string;company:string;country:string;email:string;phone:string;product:string;message:string};
function detailRow(label:string,value:string){return `<tr><td width="125" valign="top" style="border-bottom:1px solid #e2ebe0;padding:13px 0;color:#7a8b82;font-size:13px">${label}</td><td valign="top" style="border-bottom:1px solid #e2ebe0;padding:13px 0;color:#163c2e;font-size:14px;font-weight:600">${value}</td></tr>`}

function emailHtml(inquiry:Inquiry,product:string){
  const name=safe(inquiry.name),company=safe(inquiry.company||"No indicada"),country=safe(inquiry.country),email=safe(inquiry.email),phone=safe(inquiry.phone||"No indicado"),productName=safe(product),message=safe(inquiry.message).replace(/\n/g,"<br>");
  const phoneHref=inquiry.phone.replace(/[^+\d]/g,"");
  const receivedAt=new Intl.DateTimeFormat("es-PA",{dateStyle:"long",timeStyle:"short",timeZone:"America/Panama"}).format(new Date());
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nueva consulta para Panama Squash Co.</title></head>
<body style="margin:0;background:#edf3ea;color:#082d22;font-family:Arial,Helvetica,sans-serif">
<div style="display:none;max-height:0;overflow:hidden;opacity:0">${name} consulta por ${productName} desde panamasquash.com.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#edf3ea;padding:32px 12px"><tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:680px;background:#fff;border-radius:28px;overflow:hidden;box-shadow:0 18px 60px rgba(8,45,34,.12)">
<tr><td style="background:#082d22;padding:34px 40px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td width="74" valign="middle"><img src="https://www.panamasquash.com/brand/panama-squash-logo.webp" width="62" height="62" alt="Panama Squash Co." style="display:block;background:#fff;border-radius:16px;padding:5px;object-fit:contain"></td><td valign="middle"><div style="color:#fff;font-size:20px;font-weight:800;letter-spacing:-.3px">PANAMA SQUASH CO.</div><div style="margin-top:7px;color:#d9f26a;font-size:10px;font-weight:800;letter-spacing:2px;text-transform:uppercase">El milagro de la naturaleza</div></td></tr></table>
<div style="margin-top:38px;color:#d9f26a;font-size:11px;font-weight:800;letter-spacing:2px;text-transform:uppercase">Nueva consulta web</div><h1 style="margin:12px 0 10px;color:#fff;font-size:34px;line-height:1.12;letter-spacing:-1px">Un posible cliente quiere conversar.</h1><p style="margin:0;color:#b8c9c2;font-size:15px;line-height:1.6">Recibida el ${safe(receivedAt)} desde el formulario de contacto.</p></td></tr>
<tr><td style="padding:36px 40px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eff6e8;border-radius:20px"><tr><td style="padding:22px 24px"><div style="color:#52705f;font-size:10px;font-weight:800;letter-spacing:1.7px;text-transform:uppercase">Producto de interés</div><div style="margin-top:7px;color:#0d5b3d;font-size:24px;font-weight:800">${productName}</div></td></tr></table></td></tr>
<tr><td style="padding:16px 40px 8px"><div style="margin-bottom:14px;color:#0d5b3d;font-size:11px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase">Datos del contacto</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse">${detailRow("Nombre",name)}${detailRow("Empresa",company)}${detailRow("País",country)}${detailRow("Correo",`<a href="mailto:${email}" style="color:#0d5b3d;font-weight:700;text-decoration:none">${email}</a>`)}${detailRow("Teléfono",inquiry.phone?`<a href="tel:${safe(phoneHref)}" style="color:#0d5b3d;font-weight:700;text-decoration:none">${phone}</a>`:phone)}</table></td></tr>
<tr><td style="padding:26px 40px 8px"><div style="margin-bottom:12px;color:#0d5b3d;font-size:11px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase">Mensaje</div><div style="border-left:4px solid #d9f26a;background:#f7faf5;border-radius:0 18px 18px 0;padding:22px 24px;color:#294a3d;font-size:16px;line-height:1.7">${message}</div></td></tr>
<tr><td style="padding:30px 40px 42px"><a href="mailto:${email}?subject=${encodeURIComponent(`Re: Consulta sobre ${product}`)}" style="display:inline-block;background:#d9f26a;color:#082d22;border-radius:999px;padding:15px 24px;font-size:14px;font-weight:800;text-decoration:none">Responder a ${name} →</a></td></tr>
<tr><td style="background:#f3f7f0;border-top:1px solid #dce7d9;padding:22px 40px;color:#718379;font-size:11px;line-height:1.6">Este mensaje fue enviado desde el formulario oficial de <a href="https://www.panamasquash.com" style="color:#0d5b3d;text-decoration:none">panamasquash.com</a>. Al responder, el correo se enviará directamente al contacto.</td></tr>
</table></td></tr></table></body></html>`;
}

export async function POST(request:Request){try{const body=await request.json();const clean:Inquiry={name:String(body.name||"").trim().slice(0,120),company:String(body.company||"").trim().slice(0,160),country:String(body.country||"").trim().slice(0,100),email:String(body.email||"").trim().toLowerCase().slice(0,200),phone:String(body.phone||"").trim().slice(0,60),product:String(body.product||"").trim().slice(0,80),message:String(body.message||"").trim().slice(0,3000)};if(!clean.name||!clean.country||!emailPattern.test(clean.email)||clean.message.length<5)return NextResponse.json({error:"Datos inválidos"},{status:400});const resendKey=process.env.RESEND_API_KEY;if(!resendKey)return NextResponse.json({error:"Servicio de correo no configurado"},{status:503});const product=productNames[clean.product]||clean.product||"No especificado";const emailResponse=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.CONTACT_FROM_EMAIL||"Panama Squash Co. <formularios@panamasquash.com>",to:[process.env.CONTACT_TO_EMAIL||"info@panamasquash.com"],reply_to:clean.email,subject:`Nueva consulta · ${product} · ${clean.name}`,html:emailHtml(clean,product),text:`NUEVA CONSULTA — PANAMA SQUASH CO.\n\nNombre: ${clean.name}\nEmpresa: ${clean.company||"No indicada"}\nPaís: ${clean.country}\nCorreo: ${clean.email}\nTeléfono: ${clean.phone||"No indicado"}\nProducto: ${product}\n\nMensaje:\n${clean.message}\n\nResponde directamente a este correo para contactar a ${clean.name}.`})});if(!emailResponse.ok){console.error("Resend delivery error",emailResponse.status,await emailResponse.text());return NextResponse.json({error:"No se pudo enviar la consulta"},{status:502})}const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(url&&key){const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const{error}=await supabase.from("contact_inquiries").insert(clean);if(error)console.error("Contact inquiry storage error",error)}return NextResponse.json({ok:true},{status:201})}catch(error){console.error("Contact inquiry error",error);return NextResponse.json({error:"No se pudo procesar la consulta"},{status:500})}}
