"use client";

import{createContext,useContext,useEffect,useState}from"react";
import{usePathname}from"next/navigation";

type Language="en"|"es";
const LanguageContext=createContext<{language:Language;setLanguage:(language:Language)=>void}>({language:"en",setLanguage:()=>{}});

const translations:Record<string,string>={
  "El milagro de la naturaleza":"Nature's miracle","Inicio":"Home","Nosotros":"About","Productos":"Products","Galería":"Gallery","Noticias":"News","Contacto":"Contact","Solicitar información":"Request information","Cerrar menú":"Close menu","Abrir menú":"Open menu",
  "Agricultura panameña":"Panamanian agriculture","Cultivamos aquí.":"We grow here.","Llegamos más lejos.":"We go further.","Producimos, seleccionamos y empacamos productos agrícolas en Panamá con la calidad y consistencia que exige cada mercado.":"We grow, select and pack agricultural products in Panama with the quality and consistency each market demands.","Conoce nuestros productos":"Explore our products","Habla con nosotros":"Talk to us","Producto de Panamá":"Product of Panama",
  "Calidad que nace en el campo y se confirma en cada entrega.":"Quality that begins in the field and is proven in every delivery.","Somos una empresa panameña dedicada a producir, seleccionar, empacar y comercializar productos agrícolas de alta calidad.":"We are a Panamanian company dedicated to growing, selecting, packing and marketing high-quality agricultural products.","Trabajamos para mercados nacionales e internacionales con atención al producto, comunicación clara y una operación preparada para responder.":"We serve domestic and international markets with careful product handling, clear communication and a responsive operation.","Conoce la empresa":"Meet our company",
  "Portafolio":"Portfolio","Productos de nuestra tierra.":"Products from our land.","Selección agrícola panameña preparada según las necesidades de cada comprador.":"Panamanian produce selected and prepared for each buyer's needs.","Proceso integrado":"Integrated process","Del campo a mercados internacionales.":"From the field to international markets.","Gestionamos el producto desde la producción y selección hasta el empaque y la preparación para exportación.":"We manage products from growing and selection through packing and export preparation.","Cultivo":"Growing","Selección":"Selection","Empaque":"Packing","Logística":"Logistics","Exportación":"Export",
  "Desde Panamá":"From Panama","La tierra detrás del producto.":"The land behind every product.","Ver galería":"View gallery","Desliza para recorrer el campo, la selección y el empaque.":"Swipe through our fields, selection and packing process.","Actualidad":"Updates","Noticias desde el campo.":"News from the field.","Ver todas →":"View all →","Hablemos de su mercado":"Let's talk about your market","¿Busca un proveedor agrícola confiable?":"Looking for a reliable agricultural supplier?","Enviar una consulta":"Send an inquiry",
  "Nuestra tierra.":"Our land.","Nuestra historia.":"Our story.","Empresa familiar desde 2006":"Family-owned since 2006","Somos una empresa familiar panameña que produce, compra y exporta productos agrícolas, conectando el trabajo de nuestra región con oportunidades en mercados internacionales.":"We are a Panamanian family business that grows, purchases and exports agricultural products, connecting our region's work with opportunities in international markets.","Ubicación":"Location","Quiénes somos":"Who we are","Familia, campo y vocación exportadora.":"Family, farming and an export vocation.","Panama Squash Co. nació el":"Panama Squash Co. was founded on","22 de febrero de 2006":"February 22, 2006","como una empresa 100% familiar. Desde entonces, trabajamos junto a productores de nuestra región para ofrecer productos agrícolas de excelente calidad.":"as a 100% family-owned business. Since then, we have worked alongside growers in our region to offer outstanding agricultural products.","Producimos, compramos y exportamos distintos tipos de productos agrícolas. Somos miembros de GANTRAP y formamos parte de una comunidad productiva que comparte nuestra visión de crecimiento.":"We grow, purchase and export a range of agricultural products. We are GANTRAP members and part of a productive community that shares our vision for growth.","Año de fundación":"Year founded","Contenedores exportados":"Containers exported","Empresa familiar":"Family-owned company",
  "Nuestra trayectoria":"Our journey","Del corazón de Herrera hacia el mundo.":"From the heart of Herrera to the world.","Producción · Compra · Exportación":"Growing · Purchasing · Export","22 de febrero":"February 22","Nace Panama Squash Co.":"Panama Squash Co. is born","Iniciamos como empresa familiar, productora y agroexportadora en la provincia de Herrera.":"We began as a family-owned grower and agricultural exporter in Herrera province.","22 de enero":"January 22","Sello Panamá Exporta":"Panama Export Seal","Nos incorporamos al programa del MIDA y el MICI que brinda a empresas privadas la oportunidad de ofrecer productos panameños a nivel mundial.":"We joined the MIDA and MICI program that helps private companies offer Panamanian products worldwide.","HOY":"TODAY","Experiencia acumulada":"Proven experience","Más de 1,000 contenedores":"More than 1,000 containers","Continuamos conectando productos agrícolas de nuestra región con mercados internacionales.":"We continue connecting agricultural products from our region with international markets.",
  "Lo que nos guía":"What guides us","Crecer juntos crea mejores oportunidades.":"Growing together creates better opportunities.","Misión":"Mission","Visión":"Vision","Objetivo":"Objective","Ser una empresa líder en la exportación de productos agrícolas, satisfaciendo la demanda del mercado internacional con productos de excelente calidad y contribuyendo a mejorar las condiciones de vida de nuestros aliados estratégicos: los productores de nuestra región.":"To lead in agricultural exports by meeting international demand with outstanding products while improving quality of life for our strategic partners: the growers in our region.","Acercar las necesidades del mercado internacional a los proyectos de siembra que desarrollan nuestros productores nacionales.":"To connect international market needs with the planting projects developed by our national growers.","Brindar a nuestros clientes productos de calidad para lograr mejores precios, mayores volúmenes de venta y una preferencia especial por parte de quienes confían en nosotros.":"To provide quality products that support better prices, higher sales volumes and lasting preference from those who trust us.",
  "Compromiso social":"Social commitment","Nuestra comunidad es nuestra fortaleza.":"Our community is our strength.","Creemos que el éxito también se mide por la contribución al bienestar de la comunidad. El Barrero no es solo el lugar donde operamos: es el hogar que nos ha visto crecer.":"We believe success is also measured by our contribution to community well-being. El Barrero is not only where we operate; it is the home that has watched us grow.","Empleo local":"Local employment","Generamos oportunidades laborales ocupadas, en su mayoría, por mujeres de nuestra comunidad.":"We create local jobs held predominantly by women in our community.","Educación y comunidad":"Education and community","Apoyamos a la escuela y participamos en actividades de la iglesia de El Barrero.":"We support the local school and take part in El Barrero church activities.","Deporte":"Sports","Contribuimos a iniciativas deportivas que fortalecen la convivencia en la comunidad.":"We support sports initiatives that strengthen community life.","Productores":"Growers","Aportamos tecnología, semillas y fertilizantes a productores agrícolas de nuestra región.":"We provide technology, seeds and fertilizers to growers in our region.","Medio ambiente":"Environment","Promovemos la conservación ambiental como parte de una producción responsable.":"We promote environmental conservation as part of responsible production.","“No solo exportamos productos: exportamos esperanza, oportunidades y un futuro mejor.”":"“We do not only export products; we export hope, opportunity and a better future.”","Nuestro hogar":"Our home","Nos encontramos en Calle El Estudiante, corregimiento de El Barrero, distrito de Pesé, provincia de Herrera, Panamá.":"We are located on Calle El Estudiante in El Barrero, Pesé district, Herrera province, Panama.","Cómo contactarnos":"Contact us",
  "Portafolio agrícola":"Agricultural portfolio","Seleccionados en origen. Preparados para su mercado.":"Selected at origin. Prepared for your market.","Productos cultivados y manejados en Panamá, disponibles en formatos pensados para las necesidades de cada comprador.":"Products grown and handled in Panama, available in formats designed around each buyer's needs.","Ver producto":"View product","Más de nuestra tierra":"More from our land","Información":"Product","del producto.":"information.","La disponibilidad, los volúmenes y las condiciones comerciales se confirman en cada solicitud.":"Availability, volumes and commercial terms are confirmed with each inquiry.","Del campo al empaque":"From field to packing","Nuestra calabaza, de cerca.":"A closer look at our squash.","Una mirada a la cosecha, selección, etiquetado y preparación de nuestras variedades de calabaza.":"A look at the harvesting, selection, labeling and preparation of our squash varieties.","Cultivada en Panamá":"Grown in Panama","Nuestra sandía, de cerca.":"A closer look at our watermelon.","Conoce el cultivo, la cosecha y la cuidadosa selección de nuestra sandía.":"Discover how our watermelon is grown, harvested and carefully selected.","Dulzura tropical":"Tropical sweetness","Nuestra piña, de cerca.":"A closer look at our pineapple.","Una mirada a la frescura, selección y presentación de nuestra piña cultivada en Panamá.":"A look at the freshness, selection and presentation of our pineapple grown in Panama.",
  "Más productos de Panamá":"More products from Panama","Diversidad del campo. Un mismo compromiso con la calidad.":"Diversity from the field. One commitment to quality.","Plátano, papaya, yuca parafinada y melón Golden Honeydew seleccionados con el cuidado que distingue nuestro trabajo.":"Plantain, papaya, waxed cassava and Golden Honeydew melon selected with the care that defines our work.","Origen cuidado":"Careful origin","Trabajamos cerca del campo para cuidar el producto desde su origen.":"We work close to the field to care for every product from its origin.","Selección consistente":"Consistent selection","Revisamos condición y presentación según las necesidades de cada mercado.":"We review condition and presentation according to each market's needs.","Manejo responsable":"Responsible handling","Preparamos cada producto para conservar su calidad durante el proceso comercial.":"We prepare each product to preserve its quality throughout the commercial process.","Calidad preparada para cada destino":"Quality prepared for every destination","Atendemos cada solicitud de acuerdo con disponibilidad, destino y requerimientos del comprador.":"We handle each inquiry according to availability, destination and buyer requirements.","Consultar disponibilidad":"Check availability",
  "Nuestro origen":"Our origin","La agricultura, de cerca.":"Agriculture up close.","Una mirada a nuestros productos, campos y a los procesos detrás de cada cosecha.":"A look at our products, fields and the processes behind every harvest.","Una mirada a nuestros campos, productos y procesos.":"A look at our fields, products and processes.","Galería general":"General gallery","Imágenes de nuestra operación agrícola.":"Images from our agricultural operation.",
  "Noticias y conocimiento":"News and insights","Historias que nacen en el campo.":"Stories that begin in the field.","Información útil sobre nuestros productos, producción y el comercio agrícola que conecta a Panamá con otros mercados.":"Useful information about our products, production and the agricultural trade connecting Panama with other markets.","Lectura destacada":"Featured story","4 min de lectura":"4 min read","Más historias":"More stories","Ideas, productos y exportación":"Ideas, products and exports","Leer artículo":"Read article","Volver a noticias":"Back to news","Compartir":"Share",
  "Hablemos de su mercado.":"Let's talk about your market.","Cuéntanos qué producto y formato necesitas. Nuestro equipo revisará tu solicitud y se pondrá en contacto.":"Tell us which product and format you need. Our team will review your inquiry and get in touch.","Contacto directo":"Direct contact","Horario":"Hours","Lunes a viernes":"Monday to Friday","Sábado":"Saturday","Domingo · Cerrado":"Sunday · Closed","Nombre":"Name","Empresa":"Company","País":"Country","Correo electrónico":"Email address","Teléfono":"Phone","Producto de interés":"Product of interest","Selecciona un producto":"Select a product","Mensaje":"Message","Enviando…":"Sending…","Consulta recibida.":"Inquiry received.","Nuestro equipo revisará tu mensaje y se pondrá en contacto.":"Our team will review your message and get in touch.","No pudimos enviar el mensaje. Escríbenos directamente por correo.":"We could not send your message. Please email us directly.",
  "Calabaza":"Squash","Sandía":"Watermelon","Piña":"Pineapple","Plátano":"Plantain","Yuca parafinada":"Waxed cassava","Melón Golden Honeydew":"Golden Honeydew Melon","Otro":"Other","Explora":"Explore","Conversemos":"Let's talk","Todos los derechos reservados.":"All rights reserved.","enero":"January","febrero":"February","marzo":"March","abril":"April","mayo":"May","junio":"June","julio":"July","agosto":"August","septiembre":"September","octubre":"October","noviembre":"November","diciembre":"December","Producción":"Production",
  "Productos agrícolas cultivados, seleccionados y empacados en Panamá para conectar con mercados nacionales e internacionales.":"Agricultural products grown, selected and packed in Panama for domestic and international markets.","Producto de Panamá 🇵🇦":"Product of Panama 🇵🇦",
  "Variedades seleccionadas por su excelente textura y sabor, preparadas para mercados nacionales e internacionales.":"Varieties selected for their outstanding texture and flavor, prepared for domestic and international markets.","Arjuna F1, Arjuna Max Mejorado, Arjuna Gold, Armaya y Jinia":"Arjuna F1, Improved Arjuna Max, Arjuna Gold, Armaya and Jinia","Peso aproximado de 13 kg":"Approximate weight: 13 kg","2,000 mallas":"2,000 mesh bags",
  "Sandías seleccionadas por su color intenso, frescura y sabor definido, preparadas para distintos mercados.":"Watermelons selected for their rich color, freshness and distinctive flavor, prepared for different markets.","Variedades con semilla y sin semilla":"Seeded and seedless varieties","Calibres 3, 4, 5 y 6":"Sizes 3, 4, 5 and 6","Bines de 36, 45 y 60 unidades":"Bins of 36, 45 and 60 units","Cantidad por contenedor: 1,320 cajas de 16 kg o 60 bines de 350 a 400 kg":"Container capacity: 1,320 boxes of 16 kg or 60 bins of 350 to 400 kg",
  "Fruta naturalmente dulce, seleccionada por su color, textura y presentación consistente.":"Naturally sweet fruit selected for its color, texture and consistent presentation.","Dulzura natural":"Natural sweetness","Excelente sabor, color y textura":"Outstanding flavor, color and texture","Calibres del 6 al 10":"Sizes 6 through 10",
  "Producto agrícola seleccionado con atención a su condición, presentación y manejo para responder a las necesidades de cada mercado.":"Agricultural product selected with close attention to condition, presentation and handling for each market's needs.","Fruta tropical manejada bajo criterios de selección y calidad, desde su origen hasta la preparación para comercialización.":"Tropical fruit handled under careful selection and quality criteria, from origin through commercial preparation.","Raíces seleccionadas y preparadas para proteger su frescura, presentación y calidad durante el manejo comercial.":"Roots selected and prepared to protect freshness, presentation and quality during commercial handling.","Melones seleccionados por su uniformidad y presentación, preparados con el cuidado que exige una entrega consistente.":"Melons selected for uniformity and presentation, prepared with the care required for consistent delivery.",
  "Calidad desde el campo hasta el empaque":"Quality from field to packing","Cómo una selección cuidadosa protege cada producto durante su recorrido.":"How careful selection protects every product throughout its journey.","Panamá: origen estratégico para el comercio agrícola":"Panama: a strategic origin for agricultural trade","Condiciones tropicales y una ubicación conectada con mercados globales.":"Tropical conditions and a location connected to global markets.","Conoce nuestras variedades de calabaza":"Discover our squash varieties","Una mirada a las cualidades y formatos disponibles para compradores.":"A look at the qualities and formats available to buyers.","Este artículo inicial está preparado para actualizarse desde el panel administrativo.":"This initial article is ready to be updated from the admin panel.","La calidad comienza en el origen. El manejo del producto comienza en el campo y continúa durante la selección y el empaque. Cada etapa contribuye a la consistencia que espera el comprador.":"Quality begins at the source. Product care starts in the field and continues through selection and packing. Every stage contributes to the consistency buyers expect.","Contacta a nuestro equipo para conocer la disponibilidad, los formatos y la información comercial vigente.":"Contact our team for current availability, formats and commercial information."
};
const entries=Object.entries(translations).sort((a,b)=>b[0].length-a[0].length);
const originals=new WeakMap<Text,string>();
const originalAttributes=new WeakMap<Element,Map<string,string>>();
const translate=(value:string)=>entries.reduce((text,[es,en])=>text.replaceAll(es,en),value);

function translateText(root:Node,language:Language){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes:Text[]=root.nodeType===Node.TEXT_NODE?[root as Text]:[];while(walker.nextNode())nodes.push(walker.currentNode as Text);
  for(const node of nodes){
    const parent=node.parentElement;if(!parent||parent.closest("script,style,[data-no-translate]"))continue;
    if(!originals.has(node))originals.set(node,node.nodeValue||"");
    const original=originals.get(node)||"";
    const translated=language==="es"?original:translate(original);if(node.nodeValue!==translated)node.nodeValue=translated;
  }
  const elements:Element[]=root.nodeType===Node.ELEMENT_NODE?[root as Element,...Array.from((root as Element).querySelectorAll("*"))]:[];
  for(const element of elements){if(element.closest("[data-no-translate]"))continue;let saved=originalAttributes.get(element);if(!saved){saved=new Map;originalAttributes.set(element,saved)}for(const attribute of["aria-label","alt","title","placeholder"]){const value=element.getAttribute(attribute);if(value!==null&&!saved.has(attribute))saved.set(attribute,value);const original=saved.get(attribute);if(original!==undefined){const translated=language==="es"?original:translate(original);if(value!==translated)element.setAttribute(attribute,translated)}}}
}

export function LanguageProvider({children}:{children:React.ReactNode}){
  const pathname=usePathname();const[language,setLanguageState]=useState<Language>("en");
  function setLanguage(next:Language){setLanguageState(next);localStorage.setItem("panama-squash-language",next)}
  useEffect(()=>{const saved=localStorage.getItem("panama-squash-language");if(saved==="es"||saved==="en")queueMicrotask(()=>setLanguageState(saved))},[]);
  useEffect(()=>{if(pathname.startsWith("/admin"))return;document.documentElement.lang=language;translateText(document.body,language);const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==="characterData")translateText(record.target,language);else record.addedNodes.forEach(node=>translateText(node,language))}));observer.observe(document.body,{childList:true,characterData:true,subtree:true});return()=>observer.disconnect()},[language,pathname]);
  return <LanguageContext.Provider value={{language,setLanguage}}>{children}</LanguageContext.Provider>;
}
export const useLanguage=()=>useContext(LanguageContext);
