import{createClient}from"@supabase/supabase-js";import{gallery as fallbackGallery,posts as fallbackPosts}from"@/data/site";
export type ContentBlock={id:string;type:"paragraph"|"heading"|"image"|"video";text?:string;url?:string;alt?:string;caption?:string};
export type BlogPost={id?:string;slug:string;title:string;excerpt:string;content:string;content_blocks?:ContentBlock[];cover_image:string;category:string;published:boolean;published_at:string;date?:string;image?:string};
export type GalleryImage={id?:string;image_url:string;alt_text:string;caption?:string|null;display_order:number;collection_id?:string|null;src?:string;alt?:string};
export type GalleryCollection={id:string;title:string;description?:string|null;slug:string;display_order:number;published:boolean;images:GalleryImage[]};
function publicClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false}}):null}
const localPosts:BlogPost[]=fallbackPosts.map((p,i)=>({...p,id:`local-${i}`,content:"This initial article is ready to be updated from the admin panel.\n\nQuality begins at the source. Product care starts in the field and continues through selection and packing. Every stage contributes to the consistency buyers expect.\n\nContact our team for current availability, formats and commercial information.",cover_image:p.image,published:true,published_at:new Date(2023,8,28-i*7).toISOString()}));
const localGallery:GalleryImage[]=fallbackGallery.map((g,i)=>({id:`local-${i}`,image_url:g.src,alt_text:g.alt,display_order:i}));
export async function getPublishedPosts(){const db=publicClient();if(!db)return localPosts;const{data,error}=await db.from("posts").select("*").eq("published",true).order("published_at",{ascending:false});return error||!data?.length?localPosts:data as BlogPost[]}
export async function getPost(slug:string){const local=localPosts.find(p=>p.slug===slug);const db=publicClient();if(!db)return local;const{data}=await db.from("posts").select("*").eq("slug",slug).eq("published",true).maybeSingle();return data as BlogPost|null||local}
export async function getGalleryImages(){const db=publicClient();if(!db)return localGallery;const{data,error}=await db.from("gallery_images").select("*").order("display_order");return error||!data?.length?localGallery:data as GalleryImage[]}
export async function getGalleryCollections(){const db=publicClient();if(!db)return[{id:"general",title:"Panama Squash Co.",description:"A look at our fields, products and processes.",slug:"general",display_order:0,published:true,images:localGallery}];const[{data:collections,error:collectionError},{data:images,error:imageError}]=await Promise.all([db.from("gallery_collections").select("*").eq("published",true).order("display_order"),db.from("gallery_images").select("*").order("display_order")]);if(collectionError||imageError||!images?.length)return[{id:"general",title:"Panama Squash Co.",description:"A look at our fields, products and processes.",slug:"general",display_order:0,published:true,images:localGallery}];const groups=(collections||[]).map(collection=>({...collection,images:images.filter(image=>image.collection_id===collection.id)})).filter(collection=>collection.images.length);const ungrouped=images.filter(image=>!image.collection_id);if(ungrouped.length)groups.unshift({id:"general",title:"General gallery",description:"Images from our agricultural operation.",slug:"general",display_order:-1,published:true,images:ungrouped});return groups as GalleryCollection[]}
export function formatDate(value?:string){if(!value)return"";return new Intl.DateTimeFormat("en-US",{day:"numeric",month:"long",year:"numeric",timeZone:"America/Panama"}).format(new Date(value))}
